services:
  postgres:
    image: postgres:15
    container_name: heds-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: ${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: heds-keycloak
    command: start
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:${POSTGRES_PORT}/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_URL}
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_PROXY_HEADERS: xforwarded
      KC_SMTP_HOST: ${SMTP_HOST}
      KC_SMTP_FROM: ${SMTP_FROM}
      KC_SMTP_PORT: ${SMTP_PORT}
    depends_on:
      - postgres
    networks:
      - backend
      - prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heds-keycloak.rule=Host(`auth.heds.ehealth.hevs.ch`)"
      - "traefik.docker.network=prod"

  backend:
    build: ./backend
    container_name: heds-backend
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - backend
      - prod
    depends_on:
      - keycloak
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heds-backend.rule=Host(`api.heds.ehealth.hevs.ch`)"
      - "traefik.docker.network=prod"

  frontend:
    build: ./frontend
    container_name: heds-frontend
    networks:
      - backend
      - prod
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heds-frontend.rule=Host(`heds.ehealth.hevs.ch`)"
      - "traefik.docker.network=prod"

networks:
  backend:
    external: false
  prod:
    external: true

volumes:
  postgres_data:
